###
POST http://localhost:5000/api/v2/series/serie HTTP/1.1
Content-Type: application/json

{
  "serie": "futurama",
  "number_seasons": 5,
  "original_lenguage":"english",
  "features_seasons":[{"season_number":3, "season_name": "season 6","premier_date":"01-05-2001",
  "cast":["bender","fray","doctor",],
  "episodes":[{"episode_name":"esnusnu","time_duration":15}]}]
}
### obtener todos
GET http://localhost:5000/api/v2/series HTTP/1.1
### obtener por id
GET http://localhost:5000/api/v2/series/62438d89017b4c0e74b80836 HTTP/1.1
###
GET http://localhost:5000/api/v2/series/62438d89017b4c0e74b80836 HTTP/1.1
###
PUT http://localhost:5000/api/v2/series/ HTTP/1.1
Content-Type: application/json

{
  "number_seasons": 98
}
###
DELETE http://localhost:5000/api/v2/series/62438ff574ebfa16d569c2ce HTTP/1.1

### obtener serie donde actue un actor especifico.
GET http://localhost:5000/api/v2/series/actor/dreck HTTP/1.1

### obtener con serie por fecha de estreno.
GET http://localhost:5000/api/v2/series/fecha/01-03-2004 HTTP/1.1

